// SPDX-License-Identifier: MIT
// Automatically generated by build.sh
pragma solidity >=0.5.0;
address constant ExposedBytesLib_ADDR = address(0x001dC4c1cEFEF38a777b15aA20260a54E584b16C48);
address constant ExposedBytesUtil_ADDR = address(0x001D7022f5B17d2F8B695918FB48fa1089C9f85401);
address constant UNITROLLER_BEFORE_ADDR = address(0x0074341e87b1c4dB7D5ED95F92b37509F2525A7A90);
address constant UNITROLLER_AFTER_ADDR = address(0x004532A41E4b1871F3d0D0665A39968104B5388Eb5);
address constant ERC20_BEFORE_ADDR = address(0x005471914E4Eeb059D79B16e5109BF44c028eA309A);
address constant CErc20Immutable_BEFORE_ADDR = address(0x00068a90B711F5af62c24f0f695e2f84849Fbd28C3);
address constant ERC20_AFTER_ADDR = address(0x00E8593eFb73423D86e5F337A46B3450eEec1027c6);
address constant CErc20Immutable_AFTER_ADDR = address(0x00c51B43db0Cea40E36207993F0aB1883E7A865417);
