// SPDX-License-Identifier: MIT
// Automatically generated by build.sh
pragma solidity >=0.5.0;
address constant MintableToken_ADDR = address(0x001dC4c1cEFEF38a777b15aA20260a54E584b16C48);
address constant ExposedBytesLib_ADDR = address(0x001D7022f5B17d2F8B695918FB48fa1089C9f85401);
address constant ExposedBytesUtil_ADDR = address(0x00871DD7C2B4b25E1Aa18728e9D5f2Af4C4e431f5c);
