// SPDX-License-Identifier: MIT
// Automatically generated by build.sh
pragma solidity >=0.5.0;
address constant ExposedBytesLib_ADDR = address(0x001dC4c1cEFEF38a777b15aA20260a54E584b16C48);
address constant ExposedBytesUtil_ADDR = address(0x001D7022f5B17d2F8B695918FB48fa1089C9f85401);
address constant UNITROLLER_BEFORE_ADDR = address(0x00b23672F74749bf7916bA6827C64111A4d6dE7f11);
address constant UNITROLLER_AFTER_ADDR = address(0x0057b7aB09008dD5eda262b160A7b0f0d17c8754B4);
address constant ERC20_BEFORE_ADDR = address(0x00E8593eFb73423D86e5F337A46B3450eEec1027c6);
address constant CErc20Immutable_BEFORE_ADDR = address(0x00c51B43db0Cea40E36207993F0aB1883E7A865417);
address constant ERC20_AFTER_ADDR = address(0x00F156FBC12dB1aB08045BE89931d4EF6A05a999cd);
address constant CErc20Immutable_AFTER_ADDR = address(0x00CFBF124a6a93e6f3A8E38bAe2c218E888f3F0dfc);
