---
name: mypy

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.rs"
    branches:
      - [main, dev]
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  build:
    name: Run mypy type checking
    runs-on: ubuntu-22.04

    steps:
      - name: Install mypy
        run: python3 -m pip install mypy==1.2.0

      - name: Check types
        run: mypy diffusc/diffusc.py